spring.application.name=milv-shop
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.h2.console.enabled=true
spring.sql.init.mode=never
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
app.admin.username=${APP_ADMIN_USERNAME}
app.admin.password=${APP_ADMIN_PASSWORD}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
