spring.application.name=milv-shop
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:/app/data/milv-shop}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pa55w.rd}
spring.h2.console.enabled=true
spring.sql.init.mode=never
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
app.admin.username=${APP_ADMIN_USERNAME:admin}
app.admin.password=${APP_ADMIN_PASSWORD:password}
jwt.secret=${JWT_SECRET:Rtnp46yzxeHlFVun6ON+q584gvGTJ9kgBoVkHkN34h8=}
jwt.expiration=${JWT_EXPIRATION:9000000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
